---

sudo: false

os:
  - linux
  - osx

language: ruby

before_install:
  - rvm reinstall $TRAVIS_RUBY_VERSION --patch
      https://github.com/k0kubun/ruby/commit/6747055326e634899f0efb0ba7cf46.patch

install:
  - gem update --system --no-document || test true
  - gem install bundler --no-document || test true
  - bundle install --jobs 3 --retry 3

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - bundle exec rake clobber compile test
  - if [ $TRAVIS_OS_NAME = linux ]; then
      bundle exec rake sign_hooks overcommit;
    fi

rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head

env:
  - CC=gcc
  - CC=clang

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.0.0

  fast_finish: true

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
  apt:
    sources:
      - trusty
      - debian-sid
    packages:
      - indent
      - shellcheck
